server:
    port: 8888

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri:
                    searchPaths:
                        - config-repo
                    clone-on-start: true